name: Deploy HTML to EC2

on:
  push:
    branches: [ main ]  # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo $EC2_SSH_KEY>>private_key.pem 
        ssh -i "private_key.pem" $EC2_USER@EC2_HOST
        git pull origin main
        echo "Run Successful"
        exit
